version: "3.4"

services:
  sample:
    image: ${DOCKER_REGISTRY-}gig.core.web.sample
    build:
      context: .
      dockerfile: samples/GiG.Core.Web.Sample/src/GiG.Core.Web.Sample/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
    depends_on:
      - fluentd
    ports:
      - "5000:8080"

  sample-ui:
    image: ${DOCKER_REGISTRY-}gig.core.web.sample.ui
    build:
      context: samples/GiG.Core.Web.Sample.UI
      dockerfile: Dockerfile
    depends_on:
      - sample
    ports:
      - "4000:8080"

  fluentd:
    image: ${DOCKER_REGISTRY-}fluentd-elasticsearch
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"