apiVersion: v1
kind: Service
metadata:
  name: sample-client
  labels:
    run: sample-client
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: sample-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-client
spec:
  selector:
    matchLabels:
      run: sample-client
  replicas: 3
  template:
    metadata:
      labels:
        run: sample-client
    spec:
      containers:
      - name: sample-client
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: PATH_BASE
          value: /api/transactions
        - name: Logging__MinimumLevel
          value: Error
        - name: Orleans__MembershipProvider__Name
          value: Kubernetes
        image: 10.2.31.220:31835/gig.core.orleans.sample.client:20190930
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: actuator/health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10