version: "3.4"

services:
  sample-silo:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.sample.silo
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.Sample.Silo/Dockerfile
    environment:
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
      - Orleans__MembershipProvider__Address=http://consul:8500
      - RabbitMQ__Host=rabbitmq
      - StorageProviders__SampleDb__ConnectionString=Host=sampledb;Username=postgres;Password=postgres;Database=sample
    depends_on:
      - fluentd
      - consul
      - rabbitmq
      - sample-db
    ports:
      - "8000:8080"
    restart: on-failure

  sample-web:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.sample.web
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.Sample.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PATH_BASE=/api/transactions
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
      - Orleans__MembershipProvider__Address=http://consul:8500
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - fluentd
      - sample-silo
      - consul
      - rabbitmq
    ports:
      - "7000:8080"
    restart: on-failure
  
  sample-ui:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.sample.ui
    build:
      context: ../samples/Orleans/src/GiG.Core.Orleans.Sample.UI
      dockerfile: Dockerfile
    depends_on:
      - sample-web
    ports:
      - "5000:8080"
    restart: on-failure

  sample-consumer:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.sample.consumer
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.Sample.Consumer/Dockerfile
    environment:
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
      - Orleans__MembershipProvider__Address=http://consul:8500
      - RabbitMQ__Host=rabbitmq      
    depends_on:
      - fluentd
      - sample-silo
      - consul
      - rabbitmq
    restart: on-failure

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -client 0.0.0.0"  
    ports:
    - "8500:8500"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
      
  sample-db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    ports:
    - "5432:5432"