version: "3.4"

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
  
  webapp:
    image: 'etcd'
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "7000:8080"