version: "3.4"

services:
  app:
    image: 'gig.core.performance.data.kvstores.providers.etcd.watch'   
    build:
      context: ..
      dockerfile: tests/performance/GiG.Core.Performance.Data.KVStores.Providers.Etcd.Watch/Dockerfile
    environment:
      - EtcdWatch__ConnectionString=http://etcd:2379
      - EtcdWatch__Key=etcdwatch
    depends_on:
      - etcd
      
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"