version: "3.4"

services:
  sample-silo-1:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.multicluster.silo
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.MultiCluster.Silo/Dockerfile
    environment:
      - Orleans__MembershipProvider__Address=http://consul:8500
      - RabbitMQ__Host=rabbitmq
      - Orleans__Cluster__ClusterId=dev1
      - Echo_Grain_Name=Grain_In_Cluster_Dev1
    depends_on:
      - consul
    ports:
      - "8000:8080"
    restart: on-failure

  sample-silo-2:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.multicluster.silo
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.MultiCluster.Silo/Dockerfile
    environment:
      - Orleans__MembershipProvider__Address=http://consul:8500
      - RabbitMQ__Host=rabbitmq
      - Orleans__Cluster__ClusterId=dev2
      - Echo_Grain_Name=Grain_In_Cluster_Dev2
    depends_on:
      - consul
    ports:
      - "8001:8081"
    restart: on-failure

  sample-client:
    image: ${DOCKER_REGISTRY-}gig.core.orleans.multicluster.client
    build:
      context: ..
      dockerfile: samples/Orleans/src/GiG.Core.Orleans.MultiCluster.Client/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PATH_BASE=/api
      - Orleans__MembershipProvider__Address=http://consul:8500
    depends_on:
      - sample-silo-1
      - sample-silo-2
      - consul
    ports:
      - "7000:8080"
    restart: on-failure
      
  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -client 0.0.0.0"  
    ports:
    - "8500:8500"  