version: "3.4"

services:
  performance-orleans-streams-producer:
    image: ${DOCKER_REGISTRY-}gig.core.performance.orleans.streams.producer
    build:
      context: ..
      dockerfile: tests/performance/GiG.Core.Performance.Orleans.Streams.Producer/Dockerfile
    environment:
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
      - Orleans__MembershipProvider__Address=http://consul:8500
    depends_on:
      - fluentd
      - consul
    ports:
      - "8000:8080"

  performance-orleans-streams-consumer:
    image: ${DOCKER_REGISTRY-}gig.core.performance.orleans.streams.consumer
    build:
      context: ..
      dockerfile: tests/performance/GiG.Core.Performance.Orleans.Streams.Consumer/Dockerfile
    environment:
      - Logging__Sinks__Fluentd__IsEnabled=true
      - Logging__Sinks__Fluentd__Hostname=fluentd
      - Orleans__MembershipProvider__Address=http://consul:8500
    depends_on:
      - fluentd
      - performance-orleans-streams-producer
      - consul
    restart: on-failure

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -client 0.0.0.0"  
    ports:
    - "8500:8500"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021